Change Falcons Motors to Neos
FRCTeam3255/2022_Offbot_Code pull request #134
Opened 2024-04-13 02:58 UTC by Alenguye582

2024-04-13 07:45 UTC, TaylerUva commented
Looks like the build failed. I think we need to update the project to W
PILib 2024

2024-04-20 03:14 UTC, TaylerUva requested changes

2024-04-20 03:14 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Climber/MoveClimber.java
> +
this safety code should be moved into the set speed method

2024-04-20 03:14 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Climber.java
> +  // @Override
is this commented out for a reason?

2024-04-20 03:14 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Climber/MoveClimber.java
> +
also the logic should be (at bottom) **OR** (at top) current it is an **AND**

2024-04-20 03:14 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Hood.java
> +    hoodMotor.setSoftLimit(SoftLimitDirection.kReverse, ((float) prefHood.hoodMinDegrees.getValue()) / 360);
constHood Gear ratio should be added back

2024-04-20 03:14 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Turret.java
> +    turretMotor.setSoftLimit(SoftLimitDirection.kReverse, ((float) prefTurret.turretMinDegrees.getValue()) / 360);
you should add back gear ratio

2024-04-20 15:39 UTC, Alenguye582 commented on src/main/java/frc/robot/subsystems/Hood.java
> +    hoodMotor.setSoftLimit(SoftLimitDirection.kReverse, ((float) prefHood.hoodMinDegrees.getValue()) / 360);
the degreesToFalcon method is deprecated 🥺

2024-04-26 23:18 UTC, Alenguye582 commented
Things to check before/during testing:

- Hood: Make sure the soft limits are correct (and the units are correct) (should get the value in getAngleDegrees())
- Turret: Same as above ^^ (I did some funny math that may or may not keep the preference values the same (in degrees). If it doesn't work first try, we might just want to get new values)
- Shooter: Hopefully the new percentoutput values in the method work
- Climber: Limit switch logic (Remove the soft limits if it works)
- Drivetrain: I'm very scared and just hope it isn't dead

2024-04-27 00:18 UTC, TaylerUva requested changes

2024-04-27 00:18 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    config = rightFollow.getPIDController();
This is overwriting the variable 3 times. So this is essentially only saying     config = rightFollow.getPIDController();

You will need to create a new config for each lead. the follow should follow what ever the lead does.

Alternatively we can just remove PID from the drivetrain as it would only be used for autos which we won't be doing so your choice on that one

2024-04-27 00:18 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Hood.java
> +    hoodMotor.setIdleMode(IdleMode.kCoast);
hood should probably be swapped to break mode. not sure why we did coast

2024-04-27 00:18 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Hood.java
> +        (float) SN_Math.degreesToFalcon(prefHood.hoodMaxDegrees.getValue(), constHood.GEAR_RATIO));
Since these are NEOs and not falcons, we should probably just do (360/prefHood.hoodMaxDegrees.getValue())* constHood.GEAR_RATIO

According to REV docs sparks measure in rotations. So we need to divide our degrees by 360 to get rotations and multiply by the gear ratio to get the movement

2024-04-27 00:18 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Hood.java
> +        (float) SN_Math.degreesToFalcon(prefHood.hoodMinDegrees.getValue(), constHood.GEAR_RATIO));
Since these are NEOs and not falcons, we should probably just do (360/prefHood.hoodMaxDegrees.getValue())* constHood.GEAR_RATIO

According to REV docs sparks measure in rotations. So we need to divide our degrees by 360 to get rotations and multiply by the gear ratio to get the movement

2024-04-27 00:18 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Turret.java
> +    turretMotor.setIdleMode(IdleMode.kBrake);
Since these are NEOs and not falcons, we should probably just do (360/prefTurret.turretMaxDegrees.getValue())* constHood.GEAR_RATIO

According to REV docs sparks measure in rotations. So we need to divide our degrees by 360 to get rotations and multiply by the gear ratio to get the movement

2024-04-27 01:54 UTC, TaylerUva approved these changes

2024-04-27 01:55 UTC, merged